version: 1.2
workflows:

  - name: IsoformDiscoveryBenchmark
    subclass: WDL
    primaryDescriptorPath: /workflows/IsoformDiscoveryBenchmark.wdl
  - name: IsoQuant
    subclass: WDL
    primaryDescriptorPath: /workflows/IsoQuant.wdl
  - name: IsoQuant-v2
    subclass: WDL
    primaryDescriptorPath: /workflows/IsoQuant-v2.wdl
  - name: StringTie
    subclass: WDL
    primaryDescriptorPath: /workflows/StringTie.wdl
  - name: Bambu
    subclass: WDL
    primaryDescriptorPath: /workflows/Bambu.wdl
  - name: Flair
    subclass: WDL
    primaryDescriptorPath: /workflows/Flair.wdl
  - name: Talon
    subclass: WDL
    primaryDescriptorPath: /workflows/Talon.wdl
  - name: IsoSeq
    subclass: WDL
    primaryDescriptorPath: /workflows/IsoSeq.wdl
  - name: IsoSeq-v2
    subclass: WDL
    primaryDescriptorPath: /workflows/IsoSeq-v2.wdl
  - name: Flames
    subclass: WDL
    primaryDescriptorPath: /workflows/Flames.wdl
  - name: Flamesv2
    subclass: WDL
    primaryDescriptorPath: /workflows/Flamesv2.wdl
  - name: Cupcake
    subclass: WDL
    primaryDescriptorPath: /workflows/Cupcake.wdl
  - name: IsoformDiscoveryBenchmarkTasks
    subclass: WDL
    primaryDescriptorPath: /workflows/IsoformDiscoveryBenchmarkTasks.wdl
  - name: Mandalorion
    subclass: WDL
    primaryDescriptorPath: /workflows/Mandalorion.wdl
  - name: IsoformDiscoveryBenchmark-test
    subclass: WDL
    primaryDescriptorPath: /workflows/IsoformDiscoveryBenchmark-test.wdl
  - name: IsoformDiscoveryBenchmark-test2
    subclass: WDL
    primaryDescriptorPath: /workflows/IsoformDiscoveryBenchmark-test2.wdl
  - name: IsoformDiscoveryBenchmark-test3
    subclass: WDL
    primaryDescriptorPath: /workflows/IsoformDiscoveryBenchmark-test3.wdl
  - name: IsoformDiscoveryBenchmark-test4
    subclass: WDL
    primaryDescriptorPath: /workflows/IsoformDiscoveryBenchmark-test4.wdl
